import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, ArrowUpRight, Layers, ListChecks, MapPin, RotateCcw, ShoppingBag, Truck } from 'lucide-react';
import { availableSizes, fetchCatalog, JOBS, selections, type MaterialLine, type Product } from '@/features/landscaper-supply/catalog';
import './pages/LandscaperSupply.css';

const STORAGE_KEY = 'rls-material-list-v1';
const money = (n: number) => n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const osw = 'https://www.organicsoilwholesale.com';

const load = (): MaterialLine[] => { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(parsed) ? parsed : []; } catch { return []; } };

export default function RlsStandalone() {
  const [items, setItems] = useState<MaterialLine[]>(load);
  const [job, setJob] = useState<string>(JOBS[0]);
  const [listOpen, setListOpen] = useState(false);
  const [area, setArea] = useState('1000');
  const [depth, setDepth] = useState('1');
  const { data: products = [], isLoading, isError, refetch } = useQuery({ queryKey: ['rls-catalog'], queryFn: fetchCatalog, staleTime: 60000, retry: 1 });
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); }, [items]);
  const total = useMemo(() => items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0), [items]);
  const yards = Number(area) * Number(depth) / 324;
  const add = (product: Product, format: ReturnType<typeof availableSizes>[number], quantity: number) => setItems(previous => {
    const line: MaterialLine = { productId: product.id, productName: product.name, productSlug: product.slug, format: format.key, quantity, unitPrice: format.price, unit: format.unit, mode: [1000, 134, 3000, 1001, 111].includes(product.id) ? 'pay' : 'quote', imageUrl: product.texturePhotoUrl || product.imageUrl };
    const match = previous.findIndex(item => item.productId === line.productId && item.format === line.format);
    if (match < 0) return [...previous, line];
    return previous.map((item, index) => index === match ? { ...item, quantity: item.quantity + line.quantity } : item);
  });
  return <div className="rls">
    <div className="rls-topline"><span>ARIZONA LANDSCAPE MATERIALS</span><span>Fulfilled through Organic Soil Wholesale</span></div>
    <header className="rls-header"><a href="#top" className="rls-brand"><Layers size={32}/><span>REGENERATIVE<small>LANDSCAPER SUPPLY</small></span></a><nav><a href="#materials">Materials</a><a href="#planning">Plan your job</a><button className="rls-bag" onClick={() => setListOpen(true)}><ShoppingBag size={18}/>Material list <b>{items.length}</b></button></nav></header>
    <section id="top" className="rls-hero"><div><div className="rls-eyebrow">BUILT FOR THE WORK YOU DO</div><h1>Better ground.<br/>Better work.</h1><p>Soil, compost and mulch for landscape crews.<br/>Build a material list for the next job—<br className="rls-desktop"/>from a few bags to a bulk order.</p><div className="rls-hero-actions"><a className="rls-button rls-light" href="#materials">Build your material list <ArrowUpRight size={19}/></a><button className="rls-repeat" onClick={() => setItems(load())}><RotateCcw size={16}/>Reload saved material list</button></div><p className="rls-hero-note">Live prices and formats from Organic Soil Wholesale. Request a job quote for specialty blends, topsoil, or delivery planning.</p><div className="rls-hero-proof"><span>Current product pricing</span><span>Phoenix pickup</span><span>Jobsite delivery</span></div></div><div className="rls-hero-image"><img src="/images/optimized/mulch-texture-hand.jpg" alt="A handful of landscape mulch"/><div className="rls-photo-caption"><span>THE FOUNDATION OF A GOOD JOB.</span><span>01 / MATERIALS THAT MATTER</span></div></div></section>
    <div className="rls-service-strip"><span><MapPin size={20}/>Phoenix pickup</span><span><Truck size={20}/>Delivery planning for your site</span><span><Layers size={20}/>Bags · pallets · bulk</span></div>
    <section id="materials" className="rls-section"><div className="rls-section-heading"><div><div className="rls-eyebrow">THE CONTRACTOR LINEUP</div><h2>Start with the job.</h2></div><p>Choose a material, set the quantity,<br/>then build your list.</p></div><div className="rls-workflow"><span><b>01</b>Choose your material</span><span><b>02</b>Build your list</span><span><b>03</b>Order or request a quote</span></div><div className="rls-materials-intro"><span>Prices and formats update from the current OSW catalog.</span><span><i className="rls-dot rls-dot-direct"/> Checkout eligible</span><span><i className="rls-dot rls-dot-quote"/> Quote with the supply team</span></div><div className="rls-filters">{JOBS.map(option => <button key={option} aria-pressed={job === option} onClick={() => setJob(option)}>{option}</button>)}</div>{isLoading ? <p role="status">Loading current materials and prices…</p> : isError ? <p role="alert">Current catalog unavailable. <button className="rls-text-button" onClick={() => refetch()}>Try again</button> <a href="tel:+16232633386">Call (623) 263-3386</a></p> : <div className="rls-grid">{products.filter(product => job === JOBS[0] || selections[product.id].job === job).map(product => <Material key={product.id} product={product} add={add}/>)}</div>}<div className="rls-topsoil"><div><div className="rls-eyebrow">GRADING OR FILLING?</div><h3>Need topsoil?</h3><p>Tell the supply team the volume, site and schedule for a confirmed material and delivered price.</p></div><a className="rls-button rls-secondary" href={`${osw}/special-request`}>Ask about topsoil <ArrowUpRight size={18}/></a></div></section>
    <section id="planning" className="rls-planning"><div><div className="rls-eyebrow">MEASURE FIRST. ORDER WITH CONFIDENCE.</div><h2>How much<br/>ground to cover?</h2><p>Estimate loose material volume from area and chosen depth. Confirm the right depth with the supply team.</p></div><div className="rls-calculator"><div className="rls-calculator-fields"><label>Area (square feet)<input type="number" min="0" value={area} onChange={event => setArea(event.target.value)}/></label><label>Depth (inches)<input type="number" min="0" step="0.25" value={depth} onChange={event => setDepth(event.target.value)}/></label></div><strong>{Number.isFinite(yards) && yards > 0 ? yards.toFixed(2) : '—'} <small>cubic yards</small></strong><p>Area × depth ÷ 324. Does not include compaction or waste.</p><a href={`${osw}/special-request`}>Plan a bulk order <ArrowUpRight size={18}/></a></div></section>
    <section className="rls-section rls-fulfillment"><div><MapPin/><h3>Pick up with a plan.</h3><p>Phoenix yard: 1634 N 19th Ave. Available options are confirmed during ordering.</p></div><div><Truck/><h3>Supply the whole site.</h3><p>Delivery depends on material, load size, destination and truck access.</p></div><div><ListChecks/><h3>Repeat the good work.</h3><p>Save the list on this device. Materials always reload at current prices.</p></div></section>
    {listOpen && <div className="rls-notice rls-list-modal" role="dialog" aria-modal="true"><div><h3>Your material list</h3>{items.length ? <>{items.map(item => <div className="rls-line" key={`${item.productId}-${item.format}`}><span>{item.quantity} × {item.productName}<small>{item.format}</small></span><strong>{money(item.quantity * item.unitPrice)}</strong><button onClick={() => setItems(previous => previous.filter(line => !(line.productId === item.productId && line.format === item.format)))}>Remove</button></div>)}<div className="rls-total"><span>Estimated material subtotal</span><strong>{money(total)}</strong></div><p>Continue with the OSW team to confirm stock, pickup, delivery and payment.</p><div className="rls-actions"><a className="rls-button" href={`${osw}/products`}>Continue to ordering <ArrowRight size={18}/></a><a className="rls-button rls-secondary" href={`${osw}/special-request`}>Request a quote</a></div></> : <p>Your list is ready for a new job.</p>}</div><button aria-label="Close material list" onClick={() => setListOpen(false)}>×</button></div>}
    <footer className="rls-footer"><div className="rls-brand"><Layers size={28}/><span>REGENERATIVE<small>LANDSCAPER SUPPLY</small></span></div><p>Professional landscape materials.<br/>Ordering and fulfillment through Organic Soil Wholesale.</p><a href="tel:+16232633386" data-official-support-phone><span data-official-support-phone-text>(623) 263-3386</span></a></footer>
  </div>;
}

function Material({ product, add }: { product: Product; add: (product: Product, format: ReturnType<typeof availableSizes>[number], quantity: number) => void }) {
  const sizes = availableSizes(product); const [key, setKey] = useState(''); const [quantity, setQuantity] = useState('1'); const size = sizes.find(item => item.key === key) || sizes[0]; const direct = [1000, 134, 3000, 1001, 111].includes(product.id);
  return <article className="rls-card"><div className="rls-photo"><img src={product.texturePhotoUrl || product.imageUrl} alt={`${product.name} material`} loading="lazy"/><span>{selections[product.id].job}</span></div><div className="rls-card-body"><div className={`rls-product-status ${direct ? 'is-direct' : 'is-quote'}`}><span>{direct ? 'Ready to purchase' : 'Job quote'}</span><span>{direct ? 'Checkout eligible' : 'Confirm with supply team'}</span></div><h3>{product.name}</h3><p>{selections[product.id].use}</p>{size && <><label>Select a format<select aria-label={`${product.name} format`} value={size.key} onChange={event => setKey(event.target.value)}>{sizes.map(option => <option key={option.key} value={option.key}>{option.label} · {money(option.price)}</option>)}</select></label><div className="rls-buy"><label>Quantity<input aria-label={`${product.name} quantity`} type="number" min="1" max="9999" value={quantity} onChange={event => setQuantity(event.target.value)}/></label><div><strong>{money(size.price)}</strong><small>{size.unit} {direct ? '' : '· estimate'}</small></div></div><button className="rls-button" onClick={() => add(product, size, Math.max(1, Math.min(9999, Number(quantity) || 1)))}>Add to material list <ArrowRight size={18}/></button></>}</div></article>;
}
