-- Hidden catalog SKUs so Garden Refresh / Plus / Big Garden Setup can check out.
-- is_catalog_enabled = false keeps them off /products. Checkout needs the row for order_items FK.

insert into products (
  id,
  name,
  description,
  category,
  price,
  stock_quantity,
  display_title,
  product_type,
  slug,
  active,
  product_status,
  is_catalog_enabled,
  is_hidden,
  is_pay_and_pickup_enabled,
  is_wholesale_only,
  is_price_negotiable,
  requires_quote,
  image_url,
  size_price_options
)
values
  (
    4100,
    'Garden Refresh',
    '10-bag soil package for one 4x8 raised garden bed: 5 Nature''s Blanket Premium 2CF, 3 Simon''s Gold 1CF included, 2 Mikey''s Worm Poop 1CF. Phoenix package price $99.',
    'Package',
    9900,
    0,
    'Garden Refresh',
    'Raised garden bed package',
    'garden-refresh',
    true,
    'active',
    false,
    true,
    false,
    false,
    false,
    false,
    '/images/optimized/natures-blanket-bag-context.jpg',
    '[{"key":"10-Bag Package","label":"10-Bag Package","price":99,"msrp":"$199.45","unit":"per package"}]'::jsonb
  ),
  (
    4101,
    'Garden Refresh Plus',
    '16-bag potting soil package for one 4x8 raised garden bed: 10 PlantPal 1.5CF, 3 Nature''s Blanket Premium 2CF included, 3 Mikey''s Worm Poop 1CF. Phoenix package price $149.',
    'Package',
    14900,
    0,
    'Garden Refresh Plus',
    'Raised garden bed package',
    'garden-refresh-plus',
    true,
    'active',
    false,
    true,
    false,
    false,
    false,
    false,
    '/images/optimized/plantpal-with-veggies.jpg',
    '[{"key":"16-Bag Package","label":"16-Bag Package","price":149,"msrp":"$247.57","unit":"per package"}]'::jsonb
  ),
  (
    4102,
    'Big Garden Setup',
    '40-bag potting soil package for two to three 4x8 raised garden beds: 30 PlantPal 1.5CF, 4 Simon''s Gold 1CF, 3 Mikey''s Worm Poop 1CF, 3 Nature''s Blanket Premium 2CF. Phoenix package price $399.',
    'Package',
    39900,
    0,
    'Big Garden Setup',
    'Raised garden bed package',
    'big-garden-setup',
    true,
    'active',
    false,
    true,
    false,
    false,
    false,
    false,
    '/images/optimized/plantpal-with-veggies.jpg',
    '[{"key":"40-Bag Package","label":"40-Bag Package","price":399,"msrp":"$566.97","unit":"per package"}]'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  display_title = excluded.display_title,
  product_type = excluded.product_type,
  slug = excluded.slug,
  active = excluded.active,
  product_status = excluded.product_status,
  is_catalog_enabled = excluded.is_catalog_enabled,
  is_hidden = excluded.is_hidden,
  image_url = excluded.image_url,
  size_price_options = excluded.size_price_options,
  updated_at = now();
