import { useState } from 'react';
import { Link, useLocation } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { ArrowUpRight, ArrowRight, ShoppingBag, Truck, MapPin, RotateCcw, Layers, ListChecks } from 'lucide-react';
import RlsBrandMark from '@/components/RlsBrandMark';
import { CUSTOMER_SUPPORT_PHONE_DIAL, CUSTOMER_SUPPORT_PHONE_DISPLAY, CUSTOMER_SUPPORT_PHONE_TEL } from '@/config/contact';
import { useQuoteCart } from '@/contexts/QuoteCartContext';
import { isPayOnlineProduct } from '@shared/phoenixYardPickup.js';
import { availableSizes, fetchCatalog, JOBS, lineFor, selections, type Product } from '@/features/landscaper-supply/catalog';
import Checkout from './Checkout';
import { SimpleOrderForm } from '@/components/SimpleOrderForm';
import './LandscaperSupply.css';
const ROOT = import.meta.env.VITE_DEFAULT_BRAND === 'rls' ? '' : '/landscaper-supply';
const url = (path = '') => `${ROOT}${path || '/'}`;
const money = (n: number) => n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const SAVE_KEY = 'rls-material-list-v1';
function Material({ product, notify }: { product: Product; notify: (s: string) => void }) {
  const sizes = availableSizes(product);
  const [key, setKey] = useState('');
  const [qty, setQty] = useState('1');
  const size = sizes.find(s => s.key === key) || sizes[0];
  const { addItem } = useQuoteCart();
  const pay = isPayOnlineProduct(product.id);
  return <article className="rls-card">
    <div className="rls-photo"><img src={product.texturePhotoUrl || product.imageUrl} alt={`${product.name} material`} loading="lazy"/><span>{selections[product.id].job}</span></div>
    <div className="rls-card-body"><div className={`rls-product-status ${pay ? 'is-direct' : 'is-quote'}`}><span>{pay ? 'Ready to purchase' : 'Job quote'}</span><span>{pay ? 'Checkout eligible' : 'Confirm with supply team'}</span></div><h3>{product.name}</h3><p>{selections[product.id].use}</p>
    {size ? <><label>Select a format<select aria-label={`${product.name} format`} value={size.key} onChange={e => setKey(e.target.value)}>{sizes.map(s => <option key={s.key} value={s.key}>{s.label} · {money(s.price)}</option>)}</select></label>
    <div className="rls-buy"><label>Quantity<input aria-label={`${product.name} quantity`} type="number" min="1" max="9999" step="1" value={qty} onChange={e => setQty(e.target.value)}/></label><div><strong>{money(size.price)}</strong><small>{size.unit} {pay ? '' : '· estimate'}</small></div></div>
    <button className="rls-button" onClick={() => { try { addItem(lineFor(product, size, Number(qty))); notify(`${qty} × ${product.name} added to your material list.`); } catch(e) { notify((e as Error).message); } }}>Add to material list<ArrowRight size={18}/></button></> : <p>Contact us for available formats.</p>}
    </div></article>;
}
export default function LandscaperSupply() {
  const [location] = useLocation();
  const { items, totalPrice, addItem, removeItem, updateQuantity } = useQuoteCart();
  const [job, setJob] = useState<string>(JOBS[0]);
  const [message, setMessage] = useState('');
  const [area, setArea] = useState('1000');
  const [depth, setDepth] = useState('1');
  const { data: products = [], isLoading, isError, refetch } = useQuery({ queryKey: ['rls-catalog'], queryFn: fetchCatalog, staleTime: 60000, retry: 1 });
  const cubicYards = Number(area) * Number(depth) / 324;
  const save = () => { try { localStorage.setItem(SAVE_KEY, JSON.stringify(items.map(i => ({ id: i.productId, key: i.format, quantity: i.quantity })))); setMessage('Material list saved on this device. Reload it for your next job.'); } catch { setMessage('This browser could not save the list.'); } };
  const restore = async () => { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY) || '[]'); if (!Array.isArray(saved) || !saved.length) { setMessage('No saved list yet. Add materials, then save your list.'); return; } const live = await fetchCatalog(); let added = 0; for (const row of saved) { const p = live.find(p => p.id === row.id); const s = p && availableSizes(p).find(s => s.key === row.key); if(p && s && Number.isInteger(row.quantity) && row.quantity > 0 && row.quantity <= 9999) { addItem(lineFor(p, s, row.quantity)); added++; } } setMessage(`${added} saved selections added at current prices. ${saved.length - added} unavailable selections skipped.`); } catch { setMessage('Could not reload your list. Please try again.'); } };
  return <div className="rls">
    <Helmet><title>Regenerative Landscaper Supply | Materials for the job ahead</title><meta name="robots" content={ROOT ? 'noindex,nofollow' : 'index,follow'}/><link rel="canonical" href={ROOT ? 'https://regenerativelandscapersupply.com/' : 'https://organicsoilwholesale.com/landscaper-supply/'}/></Helmet>
    <div className="rls-topline"><span>ARIZONA LANDSCAPE MATERIALS</span><span>Fulfilled through Organic Soil Wholesale</span></div>
    <header className="rls-header"><Link href={url()} className="rls-brand"><RlsBrandMark size={36}/><span>REGENERATIVE<small>LANDSCAPER SUPPLY</small></span></Link><nav><a href={url('#materials')}>Materials</a><a href={url('#planning')}>Plan your job</a><Link href={url('/cart')} className="rls-bag"><ShoppingBag size={18}/>Material list <b>{items.length}</b></Link></nav></header>
    {location.endsWith('/checkout') || location.endsWith('/quote') ? <><div className="rls-handoff"><Link href={url('/cart')}>← Material list</Link><p>Order service, payment and fulfillment by Organic Soil Wholesale.</p></div>{location.endsWith('/checkout') ? <Checkout/> : <SimpleOrderForm/>}</> : location.endsWith('/cart') ? <section className="rls-section rls-cart"><div className="rls-eyebrow">YOUR NEXT JOB</div><h1>Your material list.</h1><p>Review quantities. Eligible products can be paid online; specialty blends need a quote.</p>{items.length ? <>{items.map(i => <div className="rls-line" key={`${i.productId}-${i.format}`}><div><h3>{i.productName}</h3><p>{i.format} · {i.mode === 'pay' ? 'Order online' : 'Quote required'}</p></div><label>Quantity<input aria-label={`${i.productName} order quantity`} type="number" min="1" max="9999" value={i.quantity} onChange={e => { const q = Number(e.target.value); if(Number.isInteger(q) && q > 0 && q <= 9999) updateQuantity(i.productId, i.format, q); }}/></label><strong>{money(i.unitPrice * i.quantity)}</strong><button onClick={() => removeItem(i.productId, i.format)}>Remove</button></div>)}<div className="rls-total"><span>Estimated material subtotal</span><strong>{money(totalPrice)}</strong></div><p>Tax, transport and applicable load discounts are confirmed in checkout or your quote. Stock and scheduling are confirmed through OSW.</p><div className="rls-actions">{items.some(i => i.mode === 'pay') && <Link className="rls-button" href={url('/checkout')}>Check out eligible items <ArrowRight size={18}/></Link>}<Link className="rls-button rls-secondary" href={url('/quote')}>Request a quote</Link><button className="rls-button rls-secondary" onClick={save}>Save material list</button></div>{items.some(i=>i.mode !== 'pay') && <p>Quote-only items stay in your list when you check out eligible items.</p>}</> : <div className="rls-empty"><p>Your list is ready for a new job.</p><Link className="rls-button" href={url()}>Browse materials <ArrowRight size={18}/></Link></div>}<button className="rls-text-button" onClick={restore}><RotateCcw size={16}/>Reload saved materials at current prices</button></section> : <>
    <section className="rls-hero"><div><div className="rls-eyebrow">BUILT FOR THE WORK YOU DO</div><h1>Better ground.<br/>Better work.</h1><p>Soil, compost and mulch for landscape crews.<br/>Build a material list for the next job—<br className="rls-desktop"/>from a few bags to a bulk order.</p><div className="rls-hero-actions"><a className="rls-button rls-light" href="#materials">Build your material list <ArrowUpRight size={19}/></a><button className="rls-repeat" onClick={restore}><RotateCcw size={16}/>Reload a saved material list</button></div><p className="rls-hero-note">Check out eligible products online. Request a job quote for specialty blends, topsoil, or delivery planning.</p><div className="rls-hero-proof"><span>Current product pricing</span><span>Phoenix pickup</span><span>Jobsite delivery</span></div></div><div className="rls-hero-image"><img src="/images/optimized/mulch-texture-hand.jpg" alt="A handful of landscape mulch"/><div className="rls-photo-caption"><span>THE FOUNDATION OF A GOOD JOB.</span><span>01 / MATERIALS THAT MATTER</span></div></div></section>
    <div className="rls-service-strip"><span><MapPin size={20}/>Phoenix pickup</span><span><Truck size={20}/>Delivery planning for your site</span><span><Layers size={20}/>Bags · pallets · bulk</span></div>
    <section id="materials" className="rls-section"><div className="rls-section-heading"><div><div className="rls-eyebrow">THE CONTRACTOR LINEUP</div><h2>Start with the job.</h2></div><p>Choose a material, set the quantity,<br/>then decide on checkout or a quote.</p></div><div className="rls-workflow" aria-label="How ordering works"><span><b>01</b>Choose your material</span><span><b>02</b>Build your list</span><span><b>03</b>Check out or request a quote</span></div><div className="rls-materials-intro"><span>Prices and formats update from the current OSW catalog.</span><span><i className="rls-dot rls-dot-direct"/> Checkout eligible</span><span><i className="rls-dot rls-dot-quote"/> Quote with the supply team</span></div><div className="rls-filters" role="group" aria-label="Filter materials by job">{JOBS.map(j => <button key={j} aria-pressed={job === j} onClick={() => setJob(j)}>{j}</button>)}</div>{isLoading ? <p role="status">Loading current materials and prices…</p> : isError ? <div role="alert">Current catalog unavailable. <button className="rls-text-button" onClick={() => refetch()}>Try again</button><a href="tel:+16232633386">Call (623) 263-3386</a></div> : <div className="rls-grid">{products.filter(p=>job === JOBS[0] || selections[p.id].job === job).map(p=><Material key={p.id} product={p} notify={setMessage}/>)}</div>}
    <div className="rls-topsoil"><div><div className="rls-eyebrow">GRADING OR FILLING?</div><h3>Need topsoil?</h3><p>Tell us the volume, site and schedule. The team will confirm the material, availability and delivered price.</p></div><Link className="rls-button rls-secondary" href={url('/quote?product=Topsoil')}>Ask about topsoil <ArrowUpRight size={18}/></Link></div></section>
    <section id="planning" className="rls-planning"><div><div className="rls-eyebrow">MEASURE FIRST. ORDER WITH CONFIDENCE.</div><h2>How much<br/>ground to cover?</h2><p>Estimate loose material volume from the area and your chosen depth. Confirm the right depth for your material and job with the supply team.</p></div><div className="rls-calculator"><div className="rls-calculator-fields"><label>Area (square feet)<input type="number" min="0" value={area} onChange={e=>setArea(e.target.value)}/></label><label>Depth (inches)<input type="number" min="0" step="0.25" value={depth} onChange={e=>setDepth(e.target.value)}/></label></div><strong>{Number.isFinite(cubicYards) && cubicYards > 0 ? cubicYards.toFixed(2) : '—'} <small>cubic yards</small></strong><p>Area × depth ÷ 324. Does not include compaction or waste. Materials sold by weight need a supplier conversion.</p><Link href={url('/quote')}>Plan a bulk order <ArrowUpRight size={18}/></Link></div></section>
    <section className="rls-section rls-fulfillment"><div><MapPin/><h3>Pick up with a plan.</h3><p>Phoenix yard: 1634 N 19th Ave. Select an eligible pickup option and available time during checkout.</p></div><div><Truck/><h3>Supply the whole site.</h3><p>Delivery depends on material, load size, destination and truck access. Confirm transport in checkout or request a job quote.</p></div><div><ListChecks/><h3>Repeat the good work.</h3><p>Save your material list on this device. Reload it for the next job with current formats and prices.</p></div></section></>}
    {message && <div className="rls-notice" role="status"><span>{message}</span><Link href={url('/cart')}>View list</Link><button aria-label="Dismiss notification" onClick={()=>setMessage('')}>×</button></div>}
    <footer className="rls-footer"><div className="rls-brand"><RlsBrandMark size={32}/><span>REGENERATIVE<small>LANDSCAPER SUPPLY</small></span></div><p>Professional landscape materials.<br/>Ordering and fulfillment through Organic Soil Wholesale.</p><a href={CUSTOMER_SUPPORT_PHONE_TEL} aria-label={`Call ${CUSTOMER_SUPPORT_PHONE_DISPLAY}`} data-official-support-phone="true" data-phone-number={CUSTOMER_SUPPORT_PHONE_DIAL} data-callrail-ignore="true" data-dynamic-number-ignore="true" data-call-tracking-ignore="true" className="no-call-tracking"><span data-official-support-phone-text>{CUSTOMER_SUPPORT_PHONE_DISPLAY}</span></a><div><Link href="/terms">Terms</Link> · <Link href="/privacy">Privacy</Link></div></footer>
  </div>;
}
