/* oxlint-disable next/no-img-element -- Original brand assets. */
import { ArrowUpRight, Phone, Mail, MessageCircle, Download, MapPin } from 'lucide-react';
import data from './representative-card-data.json';
import { useEffect } from 'react';
import { Helmet } from 'react-helmet-async';
import { useLocation } from 'wouter';
import './representative-card.css';
export const people=data;
export type Person=keyof typeof people;
export function BrandLogo(){return <div className="skb-logo"><img src="/representative-assets/sabrina-kills-bugs-white.png" alt="Sabrina Kills Bugs"/></div>}
export function Socials(){return <section className="socials" aria-label="Soil Seed & Water social channels"><p className="eyebrow">FOLLOW SOIL SEED & WATER</p><div><a href="https://www.instagram.com/soilseedandwater/"><img src="/representative-assets/social/instagram.svg" alt="" aria-hidden="true"/>Instagram<ArrowUpRight size={13}/></a><a href="https://www.facebook.com/profile.php?id=100083162860601"><img src="/representative-assets/social/facebook.svg" alt="" aria-hidden="true"/>Facebook<ArrowUpRight size={13}/></a><a href="https://www.tiktok.com/@soilseedandwaterusa"><img src="/representative-assets/social/tiktok.svg" alt="" aria-hidden="true"/>TikTok<ArrowUpRight size={13}/></a><a href="https://www.youtube.com/@soilseedwater"><img src="/representative-assets/social/youtube.svg" alt="" aria-hidden="true"/>YouTube<ArrowUpRight size={13}/></a></div></section>}
export function Profile({id}:{id:Person}){const p=people[id];return <article className="profile">
  <header className="profile-top"><img src="/representative-assets/ssw-logo.png" alt="Soil Seed & Water"/><span>PHOENIX, ARIZONA</span></header>
  <section className="identity"><span className="monogram" aria-hidden="true">{p.initials}</span><p className="eyebrow">YOUR SOIL CONNECTION</p><h1>{p.name}</h1><p className="role">{p.role} <span> / </span> Soil Seed & Water</p><p className="intro">Let&apos;s find the right soil<br/>for what you&apos;re growing.</p>
  <div className="contact-actions">{p.tel&&<><a href={`tel:${p.tel}`}><Phone size={19}/>Call</a><a href={`sms:${p.tel}`}><MessageCircle size={19}/>Text</a></>}{p.email&&<a href={`mailto:${p.email}`}><Mail size={19}/>Email</a>}</div>{!p.tel&&<p className="pending">Direct phone number pending</p>}<a className="save" href={`/representative-assets/${id}.vcf`} download><Download size={18}/> Save my contact</a></section>
  <section className="destinations" aria-label="Shop with us"><p className="eyebrow">WHERE WOULD YOU LIKE TO GROW?</p><a className="destination local" href={`https://www.organicsoilwholesale.com/?utm_source=representative&utm_medium=profile&utm_content=${id}`}><span className="tag">LOCAL SOIL SALES</span><h2 className="destination-logo"><img src="/representative-assets/organic-soil-wholesale-logo.svg" alt="Organic Soil Wholesale by Soil Seed & Water"/></h2><p>Soil, compost & mulch.<br/>Local pickup and bulk orders.</p><ArrowUpRight className="dest-arrow" size={25}/></a><a className="destination retail" href={`https://www.soilseedandwater.com/?utm_source=representative&utm_medium=profile&utm_content=${id}`}><span className="tag">SHOP ONLINE</span><h2 className="destination-logo ssw-destination-logo"><img src="/representative-assets/ssw-logo.png" alt="Soil Seed & Water"/></h2><p>Soil and plant nutrition,<br/>delivered to your door.</p><ArrowUpRight className="dest-arrow" size={25}/></a></section>
  {id==='sabrina'&&<section className="skb-section"><p className="eyebrow">ALSO FROM SABRINA</p><BrandLogo/><p>Sabrina&apos;s independent product line.<br/>Product questions & orders.</p><a className="skb-shop" href="https://sabrinakillsbugs.com/">Explore Sabrina Kills Bugs <ArrowUpRight size={18}/></a><a href="tel:+15204796360" className="skb-phone"><Phone size={17}/> (520) 479-6360</a><small>Personal / Sabrina Kills Bugs</small></section>}
  <Socials/><footer className="profile-footer">{p.tel&&<a href={`tel:${p.tel}`}>{p.phone}{id==='sabrina'?' · Soil sales':''}</a>}{p.email&&<a href={`mailto:${p.email}`}>{p.email}</a>}<span><MapPin size={14}/> Phoenix, Arizona</span></footer></article>}

export default function RepresentativeCardLanding(){const [location]=useLocation();const id=location.split('/')[2] as Person; const p=people[id];useEffect(()=>{const inherited=[...document.querySelectorAll('link[rel="canonical"]:not([data-rh="true"])')];inherited.forEach(node=>node.remove());return ()=>{inherited.forEach(node=>document.head.appendChild(node));};},[]);return <main className="representative-profile-page standalone no-call-tracking" data-callrail-ignore="true"><Helmet><title>{p.name} | Soil Seed &amp; Water</title><meta name="description" content={`Connect with ${p.name} at Soil Seed & Water. Local soil sales, online shopping, and direct contact details.`}/><link rel="canonical" href={`https://www.organicsoilwholesale.com/rep/${id}`}/></Helmet><Profile id={id}/></main>}
